LENGTH_FOR_NAME = 256
LENGTH_FOR_SLUG = 50
CLIPPING_LENGTH = 20
MIN_VALUE_FOR_SCORE = 1
MAX_VALUE_FOR_SCORE = 10

MAX_EMAIL_STRING = 254
MAX_CONFORMATION_CODE_STRING = 5
MAX_NAMES_STRINGS = 150
MAX_ROLES_LENGTH = 20
