# Generated by Django 3.2.25 on 2025-02-08 12:19

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250201_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username', 'role'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Можно использовать только буквы (включая буквы в верхнем и нижнем регистрах), цифры и спецсимволы: ., @, +, - ', regex='^[\\w.@+_-]+\\Z'), users.models.validate_username], verbose_name='Никнейм'),
        ),
    ]
