# Generated by Django 3.2.25 on 2025-02-10 13:30

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username_regex, users.validators.validate_username_me], verbose_name='Никнейм'),
        ),
    ]
