# Generated by Django 3.2.25 on 2024-12-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241206_1745'),
        ('users', '0003_auto_20241206_1820'),
    ]

    operations = [
    ]
