# Generated by Django 3.2.25 on 2024-12-07 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0003_auto_20241206_1745_0003_auto_20241206_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм содержит недопустимы символы!', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
