# Generated by Django 3.2 on 2024-12-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20241214_1856'),
        ('users', '0008_auto_20241222_1945'),
    ]

    operations = [
    ]
